on: [push]

jobs:
  autoBump_tag:
    runs-on: ubuntu-latest
    steps:
      - name: createTag
        uses: actions/increment-semver-patch-and-tag-action@1.2.0
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            repositoryName: ${{ github.event.repository.name }}
            repositoryOwner: ${{ github.repository_owner }}
            sha: ${{ github.sha }}
      # Use the output from the `createTag` step
      - name: Get the output tag
        run: echo "The tag was ${{ steps.createTag.outputs.newTag }}"
  